services:
  - type: web
    name: DebateChatBot
    runtime: docker
    repo: https://github.com/AluaAtykhanova/DebateChatBot.git
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: OPENAI_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TEST_ENV
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
